### ISSUE TITLE
Wunschliste ohne Anmeldung

### ISSUE THREAD

**Issue by Gniene** [Kritten/gamesdb#8]
Spiele aus der Wunschliste in die Spieleliste übertragen (Name, Bild, Beschreibung)

**Comment by Gniene** [comment]
- Itemname
- pricerange (dropdown)
- taken
- link
- picture
- description
- giftfor (Liene/Kristof/beide)

**Comment by Kritten** [comment]
Brauchen wir denk ich seit der BGG-Integration nicht mehr
